### ISSUE TITLE
prepare_simulator.sh

### ISSUE THREAD

**Issue by SunshineBrother** [louisdh/openterm#138]
Excuse me,To build for the iOS simulator, run:
./Dependencies/ios_system/Frameworks/prepare_simulator.sh，I can't find `prepare_simulator.sh`,How can I find `prepare_simulator.sh`? thank you

**Comment by louisdh** [comment]
Sorry, the README was outdated, I have updated the README with these correct instructions:

## Dependencies
To set up dependencies, run `bootstrap.sh`.

## Running
Open `OpenTerm.xcworkspace`, change the bundle identifier to an identifier linked to your Apple developer account in order to run. Build using the `OpenTerm` scheme.
