### ISSUE TITLE
New license

### ISSUE THREAD

**Issue by louisdh** [louisdh/openterm#141]
It has come to my understanding that the current MIT license is not ideal for dealing with paid OpenTerm clones on the App Store. What’s the best approach to mitigate any further scams? I’ve heard GPL might be the correct license to use here. 

To be clear: I want the license to specify that anyone can do almost anything with OpenTerm, but can not put a clone on the App Store.

**Comment by LeoNatan** [comment]
As the software owner, there is no issue with publishing GPL licensed software in the App Store. 
One pitfall to be careful of is to not be dependent on any GPL dependencies, otherwise it may not be possible to distribute. 

The best solution is to dual license the software for open source and for distribution, with the exception only granted to yourself/your company. 

I’m not sure if contributor agreement is necessary in this case, as the current license is permissive (MIT). 

It is important to note that the sooner this is done the better. The code that exist now will remain under the permissive license legally (impossible to prove that code was not formed before license change). Only new code will be covered by the new licenses, and only apps abusing that code will be taken down. 

Another important note is to keep dependencies under a permissive license.

**Comment by palmin** [comment]
@LeoNatan I'm no legal expert, but FSF clearly thinks the App Store EULA and the GPL are incompatible:
> That's the problem in a nutshell: Apple's Terms of Service impose restrictive limits on use and distribution for any software distributed through the App Store, and the GPL doesn't allow that. This specific case involves other issues, but this is the one that's most unique and deserves explanation.

https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement

I believe the existing GPL apps in the App Store are just flying under the radar but are in fact in violation.

**Comment by LeoNatan** [comment]
This is a legal problem for Apple. Since there is no clause preventing GPL software from being published, assuming no infringement on the software behalf, I think that dispute has been solved.

Even if GPL itself is not compatible, as I said and you said, it is best to have a dual-license with an exception granting additional rights to the software owner only. 

A more restrictive license, "source available"-type, can also be considered, but this is taking it too far.

**Comment by louisdh** [comment]
The easiest solution might be to follow the same license that [VLC for iOS](https://github.com/videolan/vlc-ios) uses:
"VLC-iOS is under the GPLv2 (or later) and the MPLv2 license."

https://github.com/videolan/vlc-ios/blob/master/COPYING

**Comment by louisdh** [comment]
PR: #142
