### ISSUE TITLE
Libssh missing symbols

### ISSUE THREAD

**Issue by jcampbell05** [louisdh/openterm#72]
Currently I am unable to compile master due to missing `libssh` symbols. I am not sure where these come from or how to compile the project.

Some complication instructions will be useful.

**Comment by IMcD23** [comment]
Additional steps are required for simulator builds, which is where I typically see linker errors.

Try compiling for device and report back if you’re still having issues. I agree that more instructions would be useful.

**Comment by louisdh** [comment]
The README has been updated with more detailed instructions:

## Running
Open `OpenTerm.xcworkspace`, change the bundle identifier to an identifier linked to your Apple developer account in order to run. Build using the `OpenTerm` scheme. 

### Device
Please note that by default you can only build for arm64. No further action is required.

### Simulator
To build for the iOS simulator, run:

```bash
./Dependencies/ios_system/Frameworks/prepare_simulator.sh
```
This will copy the necessary dependencies for the x86_64 architecture.

**Comment by holzschu** [comment]
It needs testing, but there are "fat" frameworks at: https://github.com/holzschu/libssh2-for-iOS/releases/ (and a script to generate them at https://github.com/holzschu/libssh2-for-iOS/ )

These contain binaries for both device and simulator. It could eliminate the need for `prepare_simulator.sh`.

**Comment by holzschu** [comment]
Sorry, strike previous comment. Fat frameworks work well for compilation (including on Travis) but break down the application signature process.

**Comment by IMcD23** [comment]
More specifically, @holzschu, FAT libraries are great for development, as they work for both `iphoneos` and `iphonesimulator` targets. However, submitting x86_64 slices to the App Store causes errors, so for release, we can't use them.
